name: fruit_quiz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fruit_basket.png
    - assets/lemon.png
    - assets/apple.png
    - assets/banana.png
    - assets/orange.png
    - assets/grapes.png
    - assets/kiwi.png
    - assets/pineapple.png
    - assets/quiz_logo2.png

  fonts:
    - family: ComicSans # Назва сімейства шрифту (можете змінити на будь-яку назву)
      fonts:
        - asset: assets/Comic Sans MS.ttf # Шлях до файлу шрифту